on:
  issues:
    types:
      - opened

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    - name: hello world action step
      id: hello
      uses: bmadjic/my-javascript-action@v20
      with:
        who-to-greet: 'Ben'
    - name:
      run: echo "The time was ${{ steps.hello.outputs.issue_name }} ${{ steps.hello.outputs.payload }}"
    - uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
