on:
  issues:
    types:
      - opened

permissions:
  contents: read
  issues: write

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    - name: hello world action step
      id: hello
      uses: bmadjic/my-javascript-action@v38
      with:
        who-to-greet: 'Ben'
    - name:
      run: echo "The time was ${{ fromJson(steps.hello.outputs.issue).title }}"
    - uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ISSUE_NAME: ${{ fromJson(steps.hello.outputs.issue).title }} [automated]
        ISSUE_LABELS: ${{ fromJson(steps.hello.outputs.issue).labels.join(', ') }} nst
      with:
        assignees: bmadjic
        update_existing: true
        search_existing: all
      id: created-issue
    - run: 'echo Created issue number ${{ steps.created-issue.outputs.number }}'
    - run: 'echo Created ${{ steps.created-issue.outputs.url }}'
