on:
  issues:
    types:
      - opened

permissions:
  contents: read
  issues: write

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    - name: hello world action step
      id: hello
      uses: bmadjic/my-javascript-action@v22
      with:
        who-to-greet: 'Ben'
    - name:
      run: echo "The time was ${{ steps.hello.outputs.issue_name }} ${{ steps.hello.outputs.payload }}"
    - uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        assignees: JasonEtco, octocat
        milestone: 1
        update_existing: true
        search_existing: all
      id: created-issue
    - run: 'echo Created issue number ${{ steps.created-issue.outputs.number }}'
    - run: 'echo Created ${{ steps.created-issue.outputs.url }}'
